/**
 * heartChat.ts
 * ─────────────────────────────────────────────────────────────────
 * Builds the Cardiac-AI keyword response map for the ChatPanel.
 *
 * Two layers:
 *   1. Static cardiac knowledge (interpolated with the user's LIVE,
 *      real metrics — no longer hardcoded constants).
 *   2. Dynamic intelligence answers (summary / risk / recommendations /
 *      report / trend) generated by cardioIntelligence so the assistant
 *      gives personalised, explainable replies instead of canned text.
 */
import type {
  CardioMetrics, RiskResult, HealthSummary, Recommendation, MetricTrend,
} from '../../services/cardioIntelligence';

interface Intel {
  risk:    RiskResult;
  summary: HealthSummary;
  recs:    Recommendation[];
  trends:  MetricTrend[];
}

export function buildHeartChatResponses(
  m: CardioMetrics & { zone: string },
  intel: Intel
): Record<string, string> {
  const { bpm, restingHr, hrv, systolic, diastolic, spo2, recovery, zone } = m;
  const bp = `${systolic}/${diastolic}`;

  // ── Dynamic intelligence answers ──────────────────────────────────
  const summaryText = `${intel.summary.headline}. ${intel.summary.paragraphs[0]}`;
  const riskText =
    `Your cardiovascular risk score is ${intel.risk.score}/100 (${intel.risk.band}). ` +
    (intel.risk.factors[0]
      ? `The biggest factor is ${intel.risk.factors[0].label.toLowerCase()}: ${intel.risk.factors[0].explanation}`
      : 'No single factor stands out — keep it up!');
  const recsText = intel.recs.length
    ? 'Top recommendations: ' + intel.recs.slice(0, 3).map((r, i) => `${i + 1}) ${r.title} — ${r.why}`).join('  ')
    : 'You have no priority recommendations right now. Keep maintaining your habits!';
  const movers = intel.trends.filter(t => t.interpretation !== 'stable');
  const trendText = movers.length
    ? 'Recent trends: ' + movers.map(t => `${t.label} is ${t.interpretation} (${t.delta > 0 ? '+' : ''}${t.delta}${t.unit})`).join(', ') + '.'
    : 'Your recent readings have been stable across all metrics — a healthy, consistent baseline.';

  const dynamic: Record<string, string> = {
    'summary':            summaryText,
    'health summary':     summaryText,
    'how am i':           summaryText,
    'overview':           summaryText,
    'risk':               riskText,
    'risk score':         riskText,
    'my risk':            riskText,
    'am i at risk':       riskText,
    'recommend':          recsText,
    'recommendation':     recsText,
    'recommendations':    recsText,
    'what should i do':   recsText,
    'advice':             recsText,
    'tips':               recsText,
    'trend':              trendText,
    'trends':             trendText,
    'weekly trend':       trendText,
    'report':             'Tap "Weekly Report" in the header to generate your full Cardiovascular Intelligence Report — it bundles your summary, risk score, trends, and recommendations, ready to print or download.',
    'weekly report':      'Your Weekly Cardiovascular Intelligence Report compiles everything: summary, risk factors, 7-reading trends and personalised actions. Open it from the "Weekly Report" button.',
  };

  // ── Static cardiac knowledge (now metric-aware) ───────────────────
  const stat: Record<string, string> = {
    'heart rate':            `Your current heart rate is ${bpm} BPM (resting ${restingHr}). Normal resting range is 60–100 BPM. You are in the ${zone} zone.`,
    'bpm':                   `Your current BPM is ${bpm}. Healthy resting target is 60–100 BPM. You are in the ${zone} zone.`,
    'pulse':                 `Your pulse is ${bpm} BPM (resting ${restingHr}), within the normal resting range.`,
    'resting heart rate':    `Your resting heart rate is ${restingHr} BPM. A healthy resting rate for adults is 60–100 BPM.`,
    'high heart rate':       'A resting heart rate consistently above 100 BPM (tachycardia) may warrant attention. Reduce caffeine and stress, and sleep well.',
    'low heart rate':        'A resting heart rate below 60 BPM (bradycardia) is common in athletes. If you feel dizzy or faint, consult a provider.',
    'heart rate zone':       `You are in the ${zone} zone (${bpm} BPM). Zones: Resting (<70), Light (70–84), Moderate (85–99), Cardio (100+).`,
    'zone':                  `Your current heart rate zone is ${zone} at ${bpm} BPM.`,
    'heart health':          `Your heart metrics: BPM ${bpm}, HRV ${hrv}ms, BP ${bp} mmHg, SpO₂ ${spo2}%. Overall risk ${intel.risk.score}/100 (${intel.risk.band}).`,
    'cardiovascular':        `Your cardiovascular risk score is ${intel.risk.score}/100 (${intel.risk.band}). Regular aerobic exercise, sleep, hydration and a balanced diet keep it low.`,
    'cardiac':               `Cardiac snapshot — BPM ${bpm}, HRV ${hrv}ms, SpO₂ ${spo2}%, BP ${bp} mmHg.`,

    'hrv':                   `Your HRV is ${hrv}ms. Higher is generally better — it reflects recovery and low physiological stress.`,
    'heart rate variability':`HRV is the variation between heartbeats. Yours is ${hrv}ms. Higher HRV means better stress resilience and recovery.`,
    'improve hrv':           'To improve HRV: prioritise sleep, manage stress, stay hydrated, exercise regularly, and limit alcohol and caffeine.',
    'recovery':              `Your recovery score is ${recovery}%. ${recovery >= 70 ? 'You are ready for moderate-to-high intensity today.' : 'Consider a lighter session or rest today.'}`,
    'recovery score':        `Your recovery score is ${recovery}%, derived from HRV, sleep and resting-heart-rate trends.`,

    'blood pressure':        `Your blood pressure is ${bp} mmHg. Ideal is below 120/80 mmHg.`,
    'bp':                    `BP reading: ${bp} mmHg. Normal is below 120/80 mmHg.`,
    'systolic':              `Your systolic pressure (top number) is ${systolic} mmHg. Normal is below 120 mmHg.`,
    'diastolic':             `Your diastolic pressure (bottom number) is ${diastolic} mmHg. Normal is below 80 mmHg.`,
    'high blood pressure':   'High blood pressure (130/80+) responds to less sodium, more movement, stress management and, if persistent, medical care.',
    'hypertension':          'Hypertension means BP consistently above 130/80 mmHg. Lifestyle changes and medical consultation are important.',

    'oxygen':                `Your SpO₂ is ${spo2}% — normal is 95–100%.`,
    'spo2':                  `SpO₂ reading: ${spo2}%.`,
    'oxygen saturation':     `Your blood oxygen saturation is ${spo2}%. Healthy range is 95–100%.`,
    'blood oxygen':          `Blood oxygen level: ${spo2}%.`,
    'low oxygen':            'SpO₂ below 94% may indicate a breathing issue. If short of breath or dizzy, seek medical attention.',
    'breathing':             `Your SpO₂ of ${spo2}% looks healthy. Slow, deep breathing can also lower your heart rate.`,

    'stress':                `Stress raises heart rate and lowers HRV. Your HRV is ${hrv}ms. Try the box-breathing exercise: inhale 4s, hold 4s, exhale 4s, hold 4s.`,
    'relax':                 'Deep breathing and mindfulness lower heart rate and raise HRV. Try box breathing or a short meditation.',
    'meditation':            'Meditation activates the parasympathetic nervous system, lowering BPM and raising HRV over time.',
    'calm':                  `To calm your heart rate (now ${bpm} BPM), try a few minutes of slow, deep breathing.`,

    'activity':              'Use "Log Reading" to record a workout plus optional BP, SpO₂ and HRV. Tracking shows how exercise affects your heart over time.',
    'log activity':          'Tap "Log Reading" in the top right to record your workout and vitals.',
    'log reading':           'Tap "Log Reading" to record heart rate, blood pressure, SpO₂ and HRV — they feed your risk score and trends.',
    'exercise':              'Regular exercise strengthens your heart, improves HRV and lowers resting BPM. Aim for 150 min of moderate activity per week.',

    'chest pain':            'Chest pain can be serious. If you feel tightness, pressure or pain — especially during/after exercise — seek medical attention immediately.',
    'palpitations':          'Palpitations are often harmless, but if frequent, prolonged, or with dizziness, consult a doctor.',
    'dizzy':                 'Dizziness can stem from low blood pressure, dehydration, or abnormal heart rate. Rest, hydrate, and monitor. See a doctor if it persists.',
    'shortness of breath':   `Shortness of breath at rest may be cardiac or respiratory. Monitor your SpO₂ (now ${spo2}%) and consult a provider if it persists.`,
    'heart attack':          'Heart attack signs: chest pain, shortness of breath, arm/jaw pain, sweating. If suspected, call emergency services immediately.',

    'hello':   `Hello! I'm your Cardiac AI. Your risk score is ${intel.risk.score}/100 (${intel.risk.band}). Ask me for a "summary", your "risk", or "recommendations".`,
    'hi':      `Hi! Your heart rate is ${bpm} BPM and risk score ${intel.risk.score}/100. Ask me about your summary, trends or recommendations.`,
    'help':    'I can give you a health summary, your risk score and why, trend analysis, and personalised recommendations — plus heart rate, HRV, BP, SpO₂ and recovery. Just ask!',
    'what can you do': 'I analyse your real readings: a plain-language summary, an explainable risk score, trend analysis, and personalised recommendations. Try "summary", "risk", or "recommendations".',
  };

  return { ...stat, ...dynamic };
}
